//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizacionBCU.UltimoCierreBCU {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsultimocierreout", Namespace="Cotiza")]
    [System.SerializableAttribute()]
    public partial class wsultimocierreout : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FechaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Cotiza", ConfigurationName="UltimoCierreBCU.wsultimocierreSoapPort")]
    public interface wsultimocierreSoapPort {
        
        // CODEGEN: Generating message contract since the wrapper name (wsultimocierre.Execute) of message ExecuteRequest does not match the default value (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="Cotizaaction/AWSULTIMOCIERRE.Execute", ReplyAction="*")]
        CotizacionBCU.UltimoCierreBCU.ExecuteResponse Execute(CotizacionBCU.UltimoCierreBCU.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Cotizaaction/AWSULTIMOCIERRE.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<CotizacionBCU.UltimoCierreBCU.ExecuteResponse> ExecuteAsync(CotizacionBCU.UltimoCierreBCU.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsultimocierre.Execute", WrapperNamespace="Cotiza", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        public ExecuteRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsultimocierre.ExecuteResponse", WrapperNamespace="Cotiza", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Cotiza", Order=0)]
        public CotizacionBCU.UltimoCierreBCU.wsultimocierreout Salida;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(CotizacionBCU.UltimoCierreBCU.wsultimocierreout Salida) {
            this.Salida = Salida;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsultimocierreSoapPortChannel : CotizacionBCU.UltimoCierreBCU.wsultimocierreSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsultimocierreSoapPortClient : System.ServiceModel.ClientBase<CotizacionBCU.UltimoCierreBCU.wsultimocierreSoapPort>, CotizacionBCU.UltimoCierreBCU.wsultimocierreSoapPort {
        
        public wsultimocierreSoapPortClient() {
        }
        
        public wsultimocierreSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsultimocierreSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsultimocierreSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsultimocierreSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CotizacionBCU.UltimoCierreBCU.ExecuteResponse CotizacionBCU.UltimoCierreBCU.wsultimocierreSoapPort.Execute(CotizacionBCU.UltimoCierreBCU.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public CotizacionBCU.UltimoCierreBCU.wsultimocierreout Execute() {
            CotizacionBCU.UltimoCierreBCU.ExecuteRequest inValue = new CotizacionBCU.UltimoCierreBCU.ExecuteRequest();
            CotizacionBCU.UltimoCierreBCU.ExecuteResponse retVal = ((CotizacionBCU.UltimoCierreBCU.wsultimocierreSoapPort)(this)).Execute(inValue);
            return retVal.Salida;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CotizacionBCU.UltimoCierreBCU.ExecuteResponse> CotizacionBCU.UltimoCierreBCU.wsultimocierreSoapPort.ExecuteAsync(CotizacionBCU.UltimoCierreBCU.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CotizacionBCU.UltimoCierreBCU.ExecuteResponse> ExecuteAsync() {
            CotizacionBCU.UltimoCierreBCU.ExecuteRequest inValue = new CotizacionBCU.UltimoCierreBCU.ExecuteRequest();
            return ((CotizacionBCU.UltimoCierreBCU.wsultimocierreSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
