//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizacionBCU.WS_CotizacionBCU {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsbcucotizacionesin", Namespace="Cotiza")]
    [System.SerializableAttribute()]
    public partial class wsbcucotizacionesin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CotizacionBCU.WS_CotizacionBCU.ArrayOfint MonedaField;
        
        private string FechaDesdeField;
        
        private string FechaHastaField;
        
        private sbyte GrupoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public CotizacionBCU.WS_CotizacionBCU.ArrayOfint Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string FechaDesde {
            get {
                return this.FechaDesdeField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaDesdeField, value) != true)) {
                    this.FechaDesdeField = value;
                    this.RaisePropertyChanged("FechaDesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string FechaHasta {
            get {
                return this.FechaHastaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaHastaField, value) != true)) {
                    this.FechaHastaField = value;
                    this.RaisePropertyChanged("FechaHasta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public sbyte Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((this.GrupoField.Equals(value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfint", Namespace="Cotiza", ItemName="item")]
    [System.SerializableAttribute()]
    public class ArrayOfint : System.Collections.Generic.List<short> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsbcucotizacionesout", Namespace="Cotiza")]
    [System.SerializableAttribute()]
    public partial class wsbcucotizacionesout : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CotizacionBCU.WS_CotizacionBCU.respuestastatus respuestastatusField;
        
        private CotizacionBCU.WS_CotizacionBCU.datoscotizaciones datoscotizacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public CotizacionBCU.WS_CotizacionBCU.respuestastatus respuestastatus {
            get {
                return this.respuestastatusField;
            }
            set {
                if ((object.ReferenceEquals(this.respuestastatusField, value) != true)) {
                    this.respuestastatusField = value;
                    this.RaisePropertyChanged("respuestastatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public CotizacionBCU.WS_CotizacionBCU.datoscotizaciones datoscotizaciones {
            get {
                return this.datoscotizacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.datoscotizacionesField, value) != true)) {
                    this.datoscotizacionesField = value;
                    this.RaisePropertyChanged("datoscotizaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="respuestastatus", Namespace="Cotiza")]
    [System.SerializableAttribute()]
    public partial class respuestastatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private sbyte statusField;
        
        private short codigoerrorField;
        
        private string mensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public sbyte status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public short codigoerror {
            get {
                return this.codigoerrorField;
            }
            set {
                if ((this.codigoerrorField.Equals(value) != true)) {
                    this.codigoerrorField = value;
                    this.RaisePropertyChanged("codigoerror");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="datoscotizaciones", Namespace="Cotiza", ItemName="datoscotizaciones.dato")]
    [System.SerializableAttribute()]
    public class datoscotizaciones : System.Collections.Generic.List<CotizacionBCU.WS_CotizacionBCU.datoscotizaciones.dato> {
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="datoscotizaciones.dato", Namespace="Cotiza")]
        [System.SerializableAttribute()]
        public partial class dato : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private string FechaField;
            
            private short MonedaField;
            
            private string NombreField;
            
            private string CodigoISOField;
            
            private string EmisorField;
            
            private double TCCField;
            
            private double TCVField;
            
            private double ArbActField;
            
            private sbyte FormaArbitrarField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public string Fecha {
                get {
                    return this.FechaField;
                }
                set {
                    if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                        this.FechaField = value;
                        this.RaisePropertyChanged("Fecha");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public short Moneda {
                get {
                    return this.MonedaField;
                }
                set {
                    if ((this.MonedaField.Equals(value) != true)) {
                        this.MonedaField = value;
                        this.RaisePropertyChanged("Moneda");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string Nombre {
                get {
                    return this.NombreField;
                }
                set {
                    if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                        this.NombreField = value;
                        this.RaisePropertyChanged("Nombre");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
            public string CodigoISO {
                get {
                    return this.CodigoISOField;
                }
                set {
                    if ((object.ReferenceEquals(this.CodigoISOField, value) != true)) {
                        this.CodigoISOField = value;
                        this.RaisePropertyChanged("CodigoISO");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
            public string Emisor {
                get {
                    return this.EmisorField;
                }
                set {
                    if ((object.ReferenceEquals(this.EmisorField, value) != true)) {
                        this.EmisorField = value;
                        this.RaisePropertyChanged("Emisor");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
            public double TCC {
                get {
                    return this.TCCField;
                }
                set {
                    if ((this.TCCField.Equals(value) != true)) {
                        this.TCCField = value;
                        this.RaisePropertyChanged("TCC");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
            public double TCV {
                get {
                    return this.TCVField;
                }
                set {
                    if ((this.TCVField.Equals(value) != true)) {
                        this.TCVField = value;
                        this.RaisePropertyChanged("TCV");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
            public double ArbAct {
                get {
                    return this.ArbActField;
                }
                set {
                    if ((this.ArbActField.Equals(value) != true)) {
                        this.ArbActField = value;
                        this.RaisePropertyChanged("ArbAct");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
            public sbyte FormaArbitrar {
                get {
                    return this.FormaArbitrarField;
                }
                set {
                    if ((this.FormaArbitrarField.Equals(value) != true)) {
                        this.FormaArbitrarField = value;
                        this.RaisePropertyChanged("FormaArbitrar");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Cotiza", ConfigurationName="WS_CotizacionBCU.wsbcucotizacionesSoapPort")]
    public interface wsbcucotizacionesSoapPort {
        
        // CODEGEN: Generating message contract since the wrapper name (wsbcucotizaciones.Execute) of message ExecuteRequest does not match the default value (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="Cotizaaction/AWSBCUCOTIZACIONES.Execute", ReplyAction="*")]
        CotizacionBCU.WS_CotizacionBCU.ExecuteResponse Execute(CotizacionBCU.WS_CotizacionBCU.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Cotizaaction/AWSBCUCOTIZACIONES.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<CotizacionBCU.WS_CotizacionBCU.ExecuteResponse> ExecuteAsync(CotizacionBCU.WS_CotizacionBCU.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsbcucotizaciones.Execute", WrapperNamespace="Cotiza", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Cotiza", Order=0)]
        public CotizacionBCU.WS_CotizacionBCU.wsbcucotizacionesin Entrada;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(CotizacionBCU.WS_CotizacionBCU.wsbcucotizacionesin Entrada) {
            this.Entrada = Entrada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsbcucotizaciones.ExecuteResponse", WrapperNamespace="Cotiza", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Cotiza", Order=0)]
        public CotizacionBCU.WS_CotizacionBCU.wsbcucotizacionesout Salida;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(CotizacionBCU.WS_CotizacionBCU.wsbcucotizacionesout Salida) {
            this.Salida = Salida;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsbcucotizacionesSoapPortChannel : CotizacionBCU.WS_CotizacionBCU.wsbcucotizacionesSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsbcucotizacionesSoapPortClient : System.ServiceModel.ClientBase<CotizacionBCU.WS_CotizacionBCU.wsbcucotizacionesSoapPort>, CotizacionBCU.WS_CotizacionBCU.wsbcucotizacionesSoapPort {
        
        public wsbcucotizacionesSoapPortClient() {
        }
        
        public wsbcucotizacionesSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsbcucotizacionesSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsbcucotizacionesSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsbcucotizacionesSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CotizacionBCU.WS_CotizacionBCU.ExecuteResponse CotizacionBCU.WS_CotizacionBCU.wsbcucotizacionesSoapPort.Execute(CotizacionBCU.WS_CotizacionBCU.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public CotizacionBCU.WS_CotizacionBCU.wsbcucotizacionesout Execute(CotizacionBCU.WS_CotizacionBCU.wsbcucotizacionesin Entrada) {
            CotizacionBCU.WS_CotizacionBCU.ExecuteRequest inValue = new CotizacionBCU.WS_CotizacionBCU.ExecuteRequest();
            inValue.Entrada = Entrada;
            CotizacionBCU.WS_CotizacionBCU.ExecuteResponse retVal = ((CotizacionBCU.WS_CotizacionBCU.wsbcucotizacionesSoapPort)(this)).Execute(inValue);
            return retVal.Salida;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CotizacionBCU.WS_CotizacionBCU.ExecuteResponse> CotizacionBCU.WS_CotizacionBCU.wsbcucotizacionesSoapPort.ExecuteAsync(CotizacionBCU.WS_CotizacionBCU.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CotizacionBCU.WS_CotizacionBCU.ExecuteResponse> ExecuteAsync(CotizacionBCU.WS_CotizacionBCU.wsbcucotizacionesin Entrada) {
            CotizacionBCU.WS_CotizacionBCU.ExecuteRequest inValue = new CotizacionBCU.WS_CotizacionBCU.ExecuteRequest();
            inValue.Entrada = Entrada;
            return ((CotizacionBCU.WS_CotizacionBCU.wsbcucotizacionesSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
